Travis silently switches to newer perl on some tests
If Travis encounters a Perl version that does not exist, it falls back to a newer version, eg: https://travis-ci.org/Perl-Toolchain-Gang/ExtUtils-MakeMaker/jobs/52743876

    $ perlbrew use 5.8.1
    ERROR: The installation "5.8.1" is unknown.
    $ perl --version
    This is perl 5, version 14, subversion 2 (v5.14.2) built for x86_64-linux-gnu-thread-multi
    (with 57 registered patches, see perl -V for more detail)

This holds true for all three digit versions and for all 5.6 versions.

Such behaviour leads to tests that pass but don't actually run on the intended platform. Thus they provide false information. Therefore this patch removes the offending patch.